version: '3.8'

services:
  ste-db-test:
    image: mysql:8
    platform: ${MYSQL_PLATFORM}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    volumes:
      - ./docker/testing-db.sql:/docker-entrypoint-initdb.d/testing-db.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME_TEST}
    networks:
      - base_net

volumes:
  node_modules:

networks:
  base_net:
    driver: bridge
